### ISSUE TITLE
Feature Request: Output to file additionally to environment variable GITHUB_STEP_SUMMARY (e.g. for docker container)

### ISSUE THREAD

**Issue by mobilizer** [rasjani/robotframework-ghareports#14]
We are currently using Robot Framework with a prebuild Docker Image (https://github.com/ppodgorsek/docker-robot-framework).

I don't want to alter the Docker Image since I don't want to maintain a custom Image.

I currently don't see a good solution to get the output in the env variable GITHUB_STEP_SUMMARY **back to** the GitHub Action or Workflow.

Could you consider **outputting the summary additionally to a file** so we could mount the directory or the file in Docker to access the summary output in the GitHub Action. And then we pass the file to the actual GITHUB_STEP_SUMMARY environment variable.

Thanks for your ideas...

**Comment by rasjani** [comment]
@mobilizer this is now released with version 0.2.0 - https://pypi.org/project/robotframework-ghareports/ 

You pass extra argument to listener to tell it to where to save the extra markdown like this:

`--listener GHAReports:60:report_file=extra_summary.md`
